### PR TITLE
Deal with expired refresh

### PR DESCRIPTION
**Pull request by brad**
@orcasgit/orcas-developers Please review. Adds an `expires_at` field and uses it for API calls, and adds a refresh_tokens management command.

### CODE REVIEW

**Comment by brad** [comment]
@grokcode OK, I think this is ready for review. I ran into some issues with tests. Django trunk is now 2.0 and there are a ton of deprecations, it's going to take some `try`/`catch`s to get things forward/backward compatible so I just dropped trunk from `tox.ini` for now. Then I remembered python 3.6 is out so I added that.

**Comment by grokcode** [comment]
@brad Looks good! I think it would be good to add some docs on the new refresh_tokens management command.

**Comment by brad** [comment]
@grokcode These docs are ready now I think. I also integrated a `docs` test environment into tox in such a way that they will get built on travis

**Comment by grokcode** [comment]
LGTM :shipit:

**Pull request merged**
